<?php

namespace Repositories;

use Ilmatar\JqGrid;

/**
 * Audit
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Audit extends JqGrid
{
    protected $listExcludeForEdit = [];
}
