<?php

namespace Repositories;

use Ilmatar\JqGrid;

/**
 * DocumentFile
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentFile extends JqGrid
{
}
