<?php
namespace Repositories;

use Ilmatar\JqGrid;

/**
 * Editorial
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Editorial extends JqGrid
{
}
