<?php
namespace Repositories;

use Ilmatar\JqGrid;

/**
 * InternalMail
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternalMail extends JqGrid
{
}
