<?php
namespace Repositories;

use Ilmatar\JqGrid;

/**
 * IpBlacklist
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpBlacklist extends JqGrid
{
}
