<?php
namespace Repositories;

use Symfony\Component\Translation\Translator;
use Symfony\Component\Routing\Generator\UrlGenerator;
use Ilmatar\JqGrid;

/**
 * Job
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Job extends JqGrid
{
    public function getJqGridColModels(Translator $translator, UrlGenerator $urlGenerator = null, array $options = [])
    {
        $columns = parent::getJqGridColModels($translator, $urlGenerator, $options);
        //Change Status filter
        foreach ($columns as $idx => $column) {
            if ('status' == $column['name']) {
                $columns[$idx]['searchoptions'] = array(
                    "sopt"  => array(self::JQGRID_OPERATOR_EQUAL),
                    "value" => self::buildSortValue(\Entities\Job::getAllStatus(), $translator)
                );
                $columns[$idx]['edittype']    = "select";
                $columns[$idx]['editoptions'] = array(
                    "value" => self::buildSortValue(\Entities\Job::getAllStatus(), $translator, false)
                );
                $columns[$idx]['stype'] = "select";
                unset($columns[$idx]['align']);
                unset($columns[$idx]['formatter']);
                break;
            } elseif (in_array($column['name'], array('code', 'description', 'class', 'run_time', 'run_counter', 'finished_at', 'status'), true)) {
                $columns[$idx]['editable'] = "false";
            }
        }
        return $columns;
    }

    public function formatJqGridRow($entity, Translator $translator, array $options = [])
    {
        $columns = parent::formatJqGridRow($entity, $translator, $options);
        //Status
        $columns['status'] = $translator->trans(\Entities\Job::getAllStatus()[$columns['status']]);
        return $columns;
    }

    public function getJobsReady()
    {
        return $this->findBy(
            array(
                'is_active' => true,
                'status'    => \Entities\job::JOB_STATUS_READY
            )
        );
    }
}
