<?php
namespace Repositories;

use Ilmatar\JqGrid;
use Carbon\Carbon;

/**
 * Mail
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mail extends JqGrid
{
    public function getMailsToSend($maxAttemptCount, $limit)
    {
        return $this
            ->createQueryBuilder('m')
            ->where('m.sent_at is NULL')
            ->andWhere('m.attempt_count < :attempt_count')
            ->orderBy('m.created_at', 'ASC')
            ->setMaxResults($limit)
            ->setParameter('attempt_count', $maxAttemptCount)
            ->getQuery()
            ->execute();
    }
    
    public function isMailExist($subject, $recipient)
    {
        return ("0" !=
            $this
            ->createQueryBuilder('m')
            ->select('COUNT(m)')
            ->where('m.object = :object')
            ->andWhere('m.recipient = :recipient')
            ->andWhere('DATE(m.sent_at) = :date')
            ->setParameter('object', $subject)
            ->setParameter('recipient', $recipient)
            ->setParameter('date', Carbon::now()->format('Y-m-d'))
            ->getQuery()
            ->getSingleScalarResult());
    }
}
