<?php
namespace Repositories;

use Ilmatar\JqGrid;

/**
 * MailTemplate
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailTemplate extends JqGrid
{
}
