<?php
namespace Repositories;

use Ilmatar\JqGrid;

/**
 * Permission
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Permission extends JqGrid
{
    /*
     * Checks if a user has a given permission (functionality, type)
     *
     * @param \Entities\User  $user
     * @param string          $functionality
     * @param integer         $type
     * @return boolean
     */
    public function isAllowedFunctionality(\Entities\User $user, $functionality, $type = \Entities\Permission::ACCESS_READ)
    {
        $role          = $user->getRole();
        $functionality = $this->getEntityManager()->getRepository('\Entities\Functionality')->findOneByCode($functionality);

        if (is_null($role) || is_null($functionality)) {
            return false;
        }

        $rights = $this->findOneBy(
            array(
                'role'          => $role,
                'functionality' => $functionality
            )
        );
        return  !is_null($rights)
           && (((\Entities\Permission::ACCESS_READWRITE == $type) && $rights->isWriteOn())
               || \Entities\Permission::ACCESS_READ == $type);
    }
}
