<?php
namespace Repositories;

use Ilmatar\JqGrid;

/**
 * RouteAnalytics
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteAnalytics extends JqGrid
{
}
