<?php
namespace Repositories;

use Ilmatar\JqGrid;

/**
 * UserSetting
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSetting extends JqGrid
{
}
