<?php
namespace Repositories;

use Ilmatar\JqGrid;

/**
 * Version
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Version extends JqGrid
{
}
